variables:
  DOCKER_IMAGE_NAME: "mitrjain1996/sbs-notification-service"
  DOCKER_VERSION: "latest"

stages:
  - build

build_image:
  stage: build
  image: docker:24.0.7-cli
  services:
   - docker:24.0.7-dind
  variables:
   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
   - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_VERSION ./backend/notification-service/

   - docker push $DOCKER_IMAGE_NAME:$DOCKER_VERSION
